---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huang.
--- DateTime: 2025/10/17 9:58
---
-- 批量更新Hash并设置过期时间
-- KEYS[1..n] = 所有的 Hash Key (e.g., blog:1, blog:2)
-- ARGV[1] = 所有的 Hash Data (JSON 字符串)
-- ARGV[2] = 基础过期时间 (秒, 默认600)
-- ARGV[3] = 随机数上限 (秒, 默认120)
local base_expire = tonumber(ARGV[2])
local rand_bound = tonumber(ARGV[3])
local data_map = cjson.decode(ARGV[1])

for _, key in ipairs(KEYS) do
    local ttl = redis.call('TTL', key)
    local hash_data = data_map[key]

    -- 批量设置Hash字段
    if hash_data and #hash_data > 0 then
        redis.call('HSET', key, unpack(hash_data))
    end

    -- 计算并设置过期时间
    local new_expire
    if ttl < base_expire then
        -- TTL < 600 (包括 -2不存在, -1永久, 或时间不足)
        new_expire = base_expire + math.random(0, rand_bound - 1)
    else
        -- TTL >= 600, 在现有基础上延长
        new_expire = ttl + math.random(0, rand_bound - 1)
    end

    redis.call('EXPIRE', key, new_expire)
end

return 1