---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huang.
--- DateTime: 2025/10/14 15:05
---
local tempThumbKey = KEYS[1]       -- 临时计数键（如 thumb:temp:{timeSlice}）
local userThumbKey = KEYS[2]       -- 用户点赞状态键（如 thumb:{userId}）
local blogKey = KEYS[3]            -- 博客键（如 blog:{blogId}）
local userId = ARGV[1]             -- 用户 ID
local blogId = ARGV[2]             -- 博客 ID

-- 1. 检查是否已点赞（避免重复操作）
if redis.call('HEXISTS', userThumbKey, blogId) == 1 then
    return -1  -- 已点赞，返回 -1 表示失败
end

-- 2. 获取旧值（不存在则默认为 0）
local hashKey = userId .. ':' .. blogId
local oldNumber = tonumber(redis.call('HGET', tempThumbKey, hashKey) or 0)

-- 3. 计算新值
local newNumber = oldNumber + 1

-- 4. 原子性更新：写入临时计数 + 标记用户已点赞
redis.call('HSET', tempThumbKey, hashKey, newNumber)
redis.call('HSET', userThumbKey, blogId, 1)

-- 5. 如果为热点/近期blog，更新blog中的点赞数+1
if redis.call('EXISTS', blogKey) == 1 then
    redis.call('HINCRBY', blogKey, 'thumbCount', 1)
end

return 1  -- 返回 1 表示成功