---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huang.
--- DateTime: 2025/10/16 16:46
---
local userThumbKey = KEYS[1]  -- redis中存储用户点赞数据的key
local blogKey = KEYS[2]       -- redis中存储blog的key（如 blog:{blogId}）
local blogId = ARGV[1]        -- 点赞的blogId
local thumbTime = ARGV[2]     -- 点赞的时间

-- 判断是否点赞
if redis.call("HEXISTS", userThumbKey, blogId) == 1 then
    -- 已点赞
    return {-1}
end

-- 添加用户点赞记录
redis.call("HSET", userThumbKey, blogId, thumbTime)
-- 如果点赞热点/近期blog，更新redis中blog的点赞数+1
if redis.call('EXISTS', blogKey) == 1 then
    redis.call('HINCRBY', blogKey, 'thumbCount', 1)
end

return {1}