---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huang.
--- DateTime: 2025/10/16 16:50
---
local userThumbKey = KEYS[1]  -- redis中存储用户点赞数据的key
local blogKey = KEYS[2]       -- redis中存储blog的key（如 blog:{blogId}）
local blogId = ARGV[1]        -- 点赞的blogId

-- 判断是否点赞
if redis.call('HEXISTS', userThumbKey, blogId) ~= 1 then
    return {-1}
end

-- 删除用户点赞记录
local thumbTime = redis.call('HGET', userThumbKey, blogId)
redis.call('HDEL', userThumbKey, blogId)
-- 如果取消点赞热点/近期blog，更新redis中blog的点赞数-1
if redis.call('EXISTS', blogKey) == 1 then
    redis.call('HINCRBY', blogKey, 'thumbCount', -1)
end

return {1, thumbTime}